-- MASTER FULL RESET & SETUP SCRIPT v2
-- This matches 'supabase_dump.sql' BUT includes the Critical Fixes for Profiles/Triggers.
-- Run this in Project: https://lfbptxisrfcnkbehzmzi.supabase.co

----------- [1. CLEANUP] -----------
-- DROP ALL TABLES in reverse dependency order
DROP TABLE IF EXISTS "public"."profiles" CASCADE;
DROP TABLE IF EXISTS "public"."social_links" CASCADE;
DROP TABLE IF EXISTS "public"."faqs" CASCADE;
DROP TABLE IF EXISTS "public"."testimonials" CASCADE;
DROP TABLE IF EXISTS "public"."team_members" CASCADE;
DROP TABLE IF EXISTS "public"."about_products" CASCADE;
DROP TABLE IF EXISTS "public"."about_stats" CASCADE;
DROP TABLE IF EXISTS "public"."about_page" CASCADE;
DROP TABLE IF EXISTS "public"."terms_page" CASCADE;
DROP TABLE IF EXISTS "public"."privacy_policy_page" CASCADE;
DROP TABLE IF EXISTS "public"."contact_messages" CASCADE;
DROP TABLE IF EXISTS "public"."site_settings" CASCADE;
DROP TABLE IF EXISTS "public"."products" CASCADE;
DROP TABLE IF EXISTS "public"."projects" CASCADE;
DROP TABLE IF EXISTS "public"."services" CASCADE;

-- Drop Triggers/Functions
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();


----------- [2. CREATE TABLES] -----------

-- 2.1 Services
CREATE TABLE "public"."services" (
    "id" text NOT NULL,
    "title" text NOT NULL,
    "description" text NOT NULL,
    "full_description" text,
    "features" text[],
    "icon_name" text NOT NULL DEFAULT 'Smartphone'::text,
    "color_theme" text DEFAULT 'from-[#3b82f6] to-[#06b6d4]'::text,
    "order_index" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone,
    "icon_url" text,
    PRIMARY KEY ("id")
);

-- 2.2 Projects
CREATE TABLE "public"."projects" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" text NOT NULL,
    "description" text NOT NULL,
    "full_description" text,
    "image_url" text,
    "tags" text[],
    "features" text[],
    "created_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

-- 2.3 Products
CREATE TABLE "public"."products" (
  "id" TEXT PRIMARY KEY,
  "title" TEXT NOT NULL,
  "short_description" TEXT NOT NULL,
  "details" TEXT,
  "image_url" TEXT,
  "price" NUMERIC,
  "features" TEXT[],
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "order_index" INTEGER DEFAULT 0
);

-- 2.4 Site Settings
CREATE TABLE "public"."site_settings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "site_name" text DEFAULT 'Portfolio'::text,
    "logo_url" text,
    "contact_email" text,
    "whatsapp_number" text,
    "play_store_url" text,
    "address" text,
    PRIMARY KEY ("id")
);

-- 2.5 Pages Content
CREATE TABLE "public"."privacy_policy_page" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "title" text DEFAULT 'Privacy Policy',
    "description" text,
    "content" text,
    "updated_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."terms_page" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "title" text DEFAULT 'Terms of Service',
    "description" text,
    "content" text,
    "updated_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."about_page" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "title" text,
    "description" text,
    "content" text,
    "updated_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

-- 2.6 About Sub-tables
CREATE TABLE "public"."about_stats" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "value" text NOT NULL,
    "label" text NOT NULL,
    "order_index" integer DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."about_products" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "title" text NOT NULL,
    "category" text,
    "description" text,
    "icon_name" text,
    "color_theme" text,
    "primary_button_text" text,
    "primary_button_link" text,
    "is_featured" boolean DEFAULT false,
    "is_coming_soon" boolean DEFAULT false,
    "features" text[],
    "order_index" integer DEFAULT 0,
    PRIMARY KEY ("id")
);

-- 2.7 Team & Testimonials
CREATE TABLE "public"."team_members" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "name" text NOT NULL,
    "role" text NOT NULL,
    "image_url" text,
    "bio" text,
    "social_links" jsonb DEFAULT '[]'::jsonb,
    "order_index" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."testimonials" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text NOT NULL,
    "role" text,
    "content" text NOT NULL,
    "image_url" text,
    "rating" integer DEFAULT 5,
    "created_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

-- 2.8 FAQs & Contact
CREATE TABLE "public"."faqs" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "question" text NOT NULL,
    "answer" text NOT NULL,
    "category" text DEFAULT 'General',
    "order_index" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."social_links" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "platform" text NOT NULL,
    "url" text NOT NULL,
    "icon_name" text,
    "order_index" integer DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."contact_messages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text NOT NULL,
    "email" text NOT NULL,
    "message" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "read" boolean DEFAULT false,
    PRIMARY KEY ("id")
);

-- 2.9 Profiles (Linked to auth.users)
CREATE TABLE "public"."profiles" (
    "id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "email" text,
    "role" text DEFAULT 'user',
    "name" text,
    "avatar_url" text,
    "created_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);


----------- [3. ENABLE RLS] -----------
ALTER TABLE "public"."services" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."projects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."site_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."contact_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."privacy_policy_page" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."terms_page" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."about_page" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."about_stats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."about_products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."team_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."testimonials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."faqs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."social_links" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


----------- [4. POLICIES] -----------
-- Public Read Access
CREATE POLICY "Public read services" ON "public"."services" FOR SELECT USING (true);
CREATE POLICY "Public read projects" ON "public"."projects" FOR SELECT USING (true);
CREATE POLICY "Public read products" ON "public"."products" FOR SELECT USING (true);
CREATE POLICY "Public read site_settings" ON "public"."site_settings" FOR SELECT USING (true);
CREATE POLICY "Public read privacy" ON "public"."privacy_policy_page" FOR SELECT USING (true);
CREATE POLICY "Public read terms" ON "public"."terms_page" FOR SELECT USING (true);
CREATE POLICY "Public read about" ON "public"."about_page" FOR SELECT USING (true);
CREATE POLICY "Public read about_stats" ON "public"."about_stats" FOR SELECT USING (true);
CREATE POLICY "Public read about_products" ON "public"."about_products" FOR SELECT USING (true);
CREATE POLICY "Public read team" ON "public"."team_members" FOR SELECT USING (true);
CREATE POLICY "Public read testimonials" ON "public"."testimonials" FOR SELECT USING (true);
CREATE POLICY "Public read faqs" ON "public"."faqs" FOR SELECT USING (true);
CREATE POLICY "Public read socials" ON "public"."social_links" FOR SELECT USING (true);
CREATE POLICY "Public read profiles" ON "public"."profiles" FOR SELECT USING (true);

-- Admin Write Access
CREATE POLICY "Admin services" ON "public"."services" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin projects" ON "public"."projects" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin products" ON "public"."products" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin site_settings" ON "public"."site_settings" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin privacy" ON "public"."privacy_policy_page" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin terms" ON "public"."terms_page" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin about" ON "public"."about_page" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin about_stats" ON "public"."about_stats" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin about_products" ON "public"."about_products" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin team" ON "public"."team_members" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin testimonials" ON "public"."testimonials" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin faqs" ON "public"."faqs" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin socials" ON "public"."social_links" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin contact_messages" ON "public"."contact_messages" FOR ALL USING (auth.role() = 'authenticated');

-- User Policies
CREATE POLICY "Users own profile" ON "public"."profiles" FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users update own profile" ON "public"."profiles" FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Public insert contact" ON "public"."contact_messages" FOR INSERT WITH CHECK (true);


----------- [5. TRIGGERS (CRITICAL FIX)] -----------

CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role, name, created_at)
  VALUES (
    NEW.id,
    NEW.email,
    'user',
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', ''),
    NEW.created_at
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


----------- [6. DATA SEEDING] -----------

-- Services
INSERT INTO "public"."services" ("id", "title", "description", "full_description", "features", "icon_name", "color_theme", "order_index") VALUES 
('android', 'Android Application Development', 'High-quality Android applications built with modern technologies.', 'We specialize in creating robust, scalable, and user-friendly Android applications.', ARRAY['Native Android (Kotlin)', 'Jetpack Compose', 'Offline-first'], 'Smartphone', 'from-[#3b82f6] to-[#06b6d4]', 1),
('ios', 'iOS Application Development', 'Professional iOS applications designed with intuitive interfaces.', 'Our iOS development team crafts elegant and powerful apps for iPhone and iPad.', ARRAY['Native iOS (Swift)', 'SwiftUI'], 'Smartphone', 'from-[#c084fc] to-[#7c3aed]', 2),
('game', 'Android Game Development', 'Engaging mobile games with stunning graphics.', 'We bring game ideas to life with Unity and modern Android game engines.', ARRAY['Unity', '2D & 3D Games'], 'Gamepad2', 'from-[#ec4899] to-[#f43f5e]', 3),
('ui-ux', 'UI/UX Design', 'Creative and intuitive user interface designs.', 'We design user interfaces that are not only visually appealing but also easy to use.', ARRAY['Figma', 'Prototyping'], 'Layout', 'from-[#f97316] to-[#ea580c]', 4);

-- Products
INSERT INTO "public"."products" ("id", "title", "short_description", "details", "image_url", "price", "features", "order_index") VALUES 
('p1', 'Premium UI Kit', 'A comprehensive UI kit.', 'Accelerate your development with our Premium UI Kit.', 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e', 49.99, ARRAY['500+ Components', 'Figma Files'], 1),
('p2', 'E-commerce Starter', 'Full-stack e-commerce template.', 'Launch your online store in days.', 'https://images.unsplash.com/photo-1556742049-0cfed4f7a07d', 199.00, ARRAY['Next.js', 'Stripe'], 2);

-- Site Settings
INSERT INTO "public"."site_settings" ("id", "site_name", "logo_url", "contact_email", "address", "play_store_url") VALUES 
(1, 'Aptic Studio', 'https://lfbptxisrfcnkbehzmzi.supabase.co/storage/v1/object/public/images/0.3098733166699379.png', 's@s.com', 'New York, USA', 'https://play.google.com/store/apps');

-- Pages
INSERT INTO "public"."privacy_policy_page" ("title", "description", "content") VALUES ('Privacy Policy', 'Our privacy commitment.', '<h1>Privacy Policy</h1><p>Content...</p>');
INSERT INTO "public"."terms_page" ("title", "description", "content") VALUES ('Terms of Service', 'Terms and conditions.', '<h1>Terms</h1><p>Content...</p>');
INSERT INTO "public"."about_page" ("title", "description", "content") VALUES ('About Us', 'Who we are.', 'We are a dev agency.');

-- About Stats
INSERT INTO "public"."about_stats" ("value", "label", "order_index") VALUES 
('50+', 'Projects', 1), ('30+', 'Clients', 2);

-- About Products
INSERT INTO "public"."about_products" ("title", "category", "description", "icon_name", "color_theme", "is_featured", "primary_button_text") VALUES 
('Aptic AI Scanner', 'Tools', 'Scanner app.', 'ScanLine', 'green', true, 'Get App');

-- Testimonials
INSERT INTO "public"."testimonials" ("name", "role", "content", "rating") VALUES 
('John Smith', 'CEO', 'Great work!', 5);

-- FAQs
INSERT INTO "public"."faqs" ("question", "answer", "category", "order_index") VALUES 
('What services?', 'Mobile & Web apps.', 'General', 1);

-- Backfill Profiles for existing users
INSERT INTO "public"."profiles" ("id", "email", "role", "name", "created_at")
SELECT 
    au.id,
    au.email,
    'user', 
    COALESCE(au.raw_user_meta_data->>'full_name', au.raw_user_meta_data->>'name', ''),
    au.created_at
FROM auth.users au
ON CONFLICT (id) DO NOTHING;


----------- [7. REFRESH CACHE] -----------
NOTIFY pgrst, 'reload schema';
