-- MASTER SQL SCRIPT: SCHEMA + STORAGE + DATA
-- This script performs a COMPLETE RESET of the project.
-- It Drops Tables, Re-creates Schema, Sets up Storage, and Seeds Dummy Data.

----------- [SECTION 1: CLEANUP] -----------
-- Drop all public tables to ensure a clean state
DROP TABLE IF EXISTS "public"."profiles" CASCADE;
DROP TABLE IF EXISTS "public"."social_links" CASCADE;
DROP TABLE IF EXISTS "public"."faqs" CASCADE;
DROP TABLE IF EXISTS "public"."testimonials" CASCADE;
DROP TABLE IF EXISTS "public"."team_members" CASCADE;
DROP TABLE IF EXISTS "public"."about_products" CASCADE;
DROP TABLE IF EXISTS "public"."about_stats" CASCADE;
DROP TABLE IF EXISTS "public"."about_page" CASCADE;
DROP TABLE IF EXISTS "public"."terms_page" CASCADE;
DROP TABLE IF EXISTS "public"."privacy_policy_page" CASCADE;
DROP TABLE IF EXISTS "public"."contact_messages" CASCADE;
DROP TABLE IF EXISTS "public"."site_settings" CASCADE;
DROP TABLE IF EXISTS "public"."products" CASCADE;
DROP TABLE IF EXISTS "public"."projects" CASCADE;
DROP TABLE IF EXISTS "public"."services" CASCADE;

-- Drop Triggers/Functions
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();


----------- [SECTION 2: SCHEMA DEFINITION] -----------

-- 2.1 Services
CREATE TABLE "public"."services" (
    "id" text NOT NULL,
    "title" text NOT NULL,
    "description" text NOT NULL,
    "full_description" text,
    "features" text[],
    "icon_name" text NOT NULL DEFAULT 'Smartphone'::text,
    "color_theme" text DEFAULT 'from-[#3b82f6] to-[#06b6d4]'::text,
    "order_index" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone,
    "icon_url" text,
    PRIMARY KEY ("id")
);

-- 2.2 Projects
CREATE TABLE "public"."projects" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" text NOT NULL,
    "description" text NOT NULL,
    "full_description" text,
    "image_url" text,
    "tags" text[],
    "features" text[],
    "created_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

-- 2.3 Products
CREATE TABLE "public"."products" (
  "id" TEXT PRIMARY KEY,
  "title" TEXT NOT NULL,
  "short_description" TEXT NOT NULL,
  "details" TEXT,
  "image_url" TEXT,
  "price" NUMERIC,
  "features" TEXT[],
  "install_link" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "order_index" INTEGER DEFAULT 0
);

-- 2.4 Site Settings
CREATE TABLE "public"."site_settings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "site_name" text DEFAULT 'Portfolio'::text,
    "logo_url" text,
    "contact_email" text,
    "whatsapp_number" text,
    "play_store_url" text,
    "address" text,
    PRIMARY KEY ("id")
);

-- 2.5 Content Pages
CREATE TABLE "public"."privacy_policy_page" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "title" text DEFAULT 'Privacy Policy',
    "description" text,
    "content" text,
    "updated_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."terms_page" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "title" text DEFAULT 'Terms of Service',
    "description" text,
    "content" text,
    "updated_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."about_page" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "title" text,
    "description" text,
    "content" text,
    "updated_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

-- 2.6 About Sub-tables
CREATE TABLE "public"."about_stats" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "value" text NOT NULL,
    "label" text NOT NULL,
    "order_index" integer DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."about_products" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "title" text NOT NULL,
    "category" text,
    "description" text,
    "icon_name" text,
    "color_theme" text,
    "primary_button_text" text,
    "primary_button_link" text,
    "is_featured" boolean DEFAULT false,
    "is_coming_soon" boolean DEFAULT false,
    "features" text[],
    "order_index" integer DEFAULT 0,
    PRIMARY KEY ("id")
);

-- 2.7 Team & Testimonials
CREATE TABLE "public"."team_members" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "name" text NOT NULL,
    "role" text NOT NULL,
    "image_url" text,
    "bio" text,
    "social_links" jsonb DEFAULT '[]'::jsonb,
    "order_index" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."testimonials" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text NOT NULL,
    "role" text,
    "content" text NOT NULL,
    "image_url" text,
    "rating" integer DEFAULT 5,
    "created_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

-- 2.8 FAQs & Contact
CREATE TABLE "public"."faqs" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "question" text NOT NULL,
    "answer" text NOT NULL,
    "category" text DEFAULT 'General',
    "order_index" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."social_links" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "platform" text NOT NULL,
    "url" text NOT NULL,
    "icon_name" text,
    "order_index" integer DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."contact_messages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text NOT NULL,
    "email" text NOT NULL,
    "message" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "read" boolean DEFAULT false,
    PRIMARY KEY ("id")
);

-- 2.9 Profiles
CREATE TABLE "public"."profiles" (
    "id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "email" text,
    "role" text DEFAULT 'user',
    "name" text,
    "avatar_url" text,
    "created_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);


----------- [SECTION 3: RLS SECURITY] -----------
ALTER TABLE "public"."services" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."projects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."site_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."contact_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."privacy_policy_page" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."terms_page" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."about_page" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."about_stats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."about_products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."team_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."testimonials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."faqs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."social_links" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;

-- 3.1 Public Read Policies
CREATE POLICY "Public read services" ON "public"."services" FOR SELECT USING (true);
CREATE POLICY "Public read projects" ON "public"."projects" FOR SELECT USING (true);
CREATE POLICY "Public read products" ON "public"."products" FOR SELECT USING (true);
CREATE POLICY "Public read site_settings" ON "public"."site_settings" FOR SELECT USING (true);
CREATE POLICY "Public read privacy" ON "public"."privacy_policy_page" FOR SELECT USING (true);
CREATE POLICY "Public read terms" ON "public"."terms_page" FOR SELECT USING (true);
CREATE POLICY "Public read about" ON "public"."about_page" FOR SELECT USING (true);
CREATE POLICY "Public read about_stats" ON "public"."about_stats" FOR SELECT USING (true);
CREATE POLICY "Public read about_products" ON "public"."about_products" FOR SELECT USING (true);
CREATE POLICY "Public read team" ON "public"."team_members" FOR SELECT USING (true);
CREATE POLICY "Public read testimonials" ON "public"."testimonials" FOR SELECT USING (true);
CREATE POLICY "Public read faqs" ON "public"."faqs" FOR SELECT USING (true);
CREATE POLICY "Public read socials" ON "public"."social_links" FOR SELECT USING (true);
CREATE POLICY "Public read profiles" ON "public"."profiles" FOR SELECT USING (true);

-- 3.2 Admin Write Policies
CREATE POLICY "Admin services" ON "public"."services" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin projects" ON "public"."projects" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin products" ON "public"."products" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin site_settings" ON "public"."site_settings" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin privacy" ON "public"."privacy_policy_page" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin terms" ON "public"."terms_page" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin about" ON "public"."about_page" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin about_stats" ON "public"."about_stats" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin about_products" ON "public"."about_products" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin team" ON "public"."team_members" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin testimonials" ON "public"."testimonials" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin faqs" ON "public"."faqs" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin socials" ON "public"."social_links" FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin contact_messages" ON "public"."contact_messages" FOR ALL USING (auth.role() = 'authenticated');

-- 3.3 User Policies
CREATE POLICY "Users own profile" ON "public"."profiles" FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users update own profile" ON "public"."profiles" FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Public insert contact" ON "public"."contact_messages" FOR INSERT WITH CHECK (true);


----------- [SECTION 4: TRIGGERS] -----------
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role, name, created_at)
  VALUES (
    NEW.id,
    NEW.email,
    'user',
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', ''),
    NEW.created_at
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


----------- [SECTION 5: STORAGE BUCKETS] -----------
-- Create 'images' bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'images' );

DROP POLICY IF EXISTS "Auth Upload" ON storage.objects;
CREATE POLICY "Auth Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'images' AND auth.role() = 'authenticated' );

DROP POLICY IF EXISTS "Auth Update" ON storage.objects;
CREATE POLICY "Auth Update" ON storage.objects FOR UPDATE USING ( bucket_id = 'images' AND auth.role() = 'authenticated' );

DROP POLICY IF EXISTS "Auth Delete" ON storage.objects;
CREATE POLICY "Auth Delete" ON storage.objects FOR DELETE USING ( bucket_id = 'images' AND auth.role() = 'authenticated' );


----------- [SECTION 6: DUMMY DATA SEEDING] -----------

-- 6.1 Services (Rich Data)
INSERT INTO "public"."services" ("id", "title", "description", "full_description", "features", "icon_name", "color_theme", "order_index") VALUES 
('android', 'Android App Development', 'Native Android apps built with Kotlin and Jetpack Compose.', 'We build high-performance, scalable, and beautiful Android applications using the latest technologies. From concept to deployment, we handle it all.', ARRAY['Kotlin & Java', 'Jetpack Compose', 'Material Design 3', 'Offline Support', 'Google Play Publishing'], 'Smartphone', 'from-[#0ea5e9] to-[#3b82f6]', 1),
('ios', 'iOS App Development', 'Premium iOS experiences using Swift and SwiftUI.', 'Crafting elegant and intuitive iOS applications that users love. We adhere to Apple Human Interface Guidelines for a native feel.', ARRAY['Swift & SwiftUI', 'UIKit Integration', 'App Store Optimization', 'Core Data & CloudKit', 'Widget Support'], 'Smartphone', 'from-[#8b5cf6] to-[#d946ef]', 2),
('web', 'Web Applications', 'Full-stack web apps with Next.js and Supabase.', 'Building modern, responsive, and SEO-friendly web applications that perform seamlessly across all devices.', ARRAY['Next.js & React', 'Supabase & PostgreSQL', 'Tailwind CSS', 'Serverless Functions', 'PWA Support'], 'Layout', 'from-[#f59e0b] to-[#ea580c]', 3),
('game', 'Game Development', 'Immersive 2D & 3D games with Unity.', 'Bringing game ideas to life with stunning visuals and engaging mechanics.', ARRAY['Unity 3D', 'C# Scripting', 'Multiplayer Networking', 'Game Design', 'Physics & Animation'], 'Gamepad2', 'from-[#ef4444] to-[#ec4899]', 4);

-- 6.2 Projects (Portfolio)
INSERT INTO "public"."projects" ("title", "description", "full_description", "image_url", "tags", "features") VALUES 
('E-Commerce Mobile App', 'A full-featured shopping app with payment integration.', '<p>A complete mobile shopping experience built for a fashion brand.</p><ul><li>User Authentication</li><li>Product Catalog</li><li>Cart & Checkout</li><li>Stripe Integration</li></ul>', 'https://images.unsplash.com/photo-1523206489230-c012c64b2b48?auto=format&fit=crop&q=80&w=800', ARRAY['Android', 'Kotlin', 'E-commerce'], ARRAY['Payment Gateway', 'Push Notifications']),
('Fitness Tracker', 'Track workouts and monitor health progress.', '<p>A health assistant app that helps users track their daily activities.</p>', 'https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&q=80&w=800', ARRAY['iOS', 'HealthKit', 'SwiftUI'], ARRAY['Step Counting', 'Calorie Tracker']),
('Admin Dashboard Pro', 'Comprehensive admin panel for managing SaaS data.', '<p>A powerful dashboard for analytics and user management.</p>', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800', ARRAY['Web', 'Next.js', 'Dashboard'], ARRAY['Analytics Charts', 'User Roles', 'Data Export']);

-- 6.3 Products (Digital Goods)
INSERT INTO "public"."products" ("id", "title", "short_description", "details", "image_url", "price", "features", "order_index") VALUES 
('p1', 'Ultimate UI Kit', '200+ Components for React & Next.js', 'Save hundreds of hours with our pre-built component library.', 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&q=80&w=800', 49.00, ARRAY['Accessible', 'Dark Mode', 'Figma Files Included'], 1),
('p2', 'SaaS Starter Boilerplate', 'Launch your SaaS in a weekend.', 'Complete authentication, payments, and dashboard setup.', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800', 149.00, ARRAY['Next.js 14', 'Supabase Auth', 'Stripe Subscriptions'], 2),
('p3', '3D Game Assets Pack', 'Low-poly assets for Unity.', 'Ready-to-use models for your next RPG game.', 'https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&q=80&w=800', 29.00, ARRAY['Characters', 'Environment', 'Props', 'Rigged Models'], 3);

-- 6.4 Team Members
INSERT INTO "public"."team_members" ("name", "role", "image_url", "bio", "social_links") VALUES 
('Sarah Johnson', 'Lead Designer', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400', 'Passionate about creating intuitive and beautiful user interfaces.', '[{"platform": "Twitter", "url": "#"}, {"platform": "LinkedIn", "url": "#"}]'::jsonb),
('Michael Chen', 'Senior Developer', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400', 'Full-stack wizard with a love for clean code and performance.', '[{"platform": "GitHub", "url": "#"}, {"platform": "LinkedIn", "url": "#"}]'::jsonb),
('Emily Davis', 'Project Manager', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=400', 'Keeping projects on track and clients happy.', '[{"platform": "LinkedIn", "url": "#"}]'::jsonb);

-- 6.5 Testimonials
INSERT INTO "public"."testimonials" ("name", "role", "content", "rating", "image_url") VALUES 
('Alex Rivera', 'CTO, TechCorp', 'The team delivered our app ahead of schedule and it looks amazing. Highly recommended!', 5, 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200'),
('Lisa Wong', 'Founder, StyleIt', 'Their design skills are top-notch. Our users love the new interface.', 5, 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200'),
('David Smith', 'Director, EduLearn', 'Professional, responsive, and technically proficient. A great partner to work with.', 4, NULL);

-- 6.6 FAQs
INSERT INTO "public"."faqs" ("question", "answer", "category", "order_index") VALUES 
('What is your typical project timeline?', 'Most mobile app projects take between 8-12 weeks, depending on complexity.', 'General', 1),
('Do you offer post-launch support?', 'Yes, we provide 3 months of free support and offer maintenance packages thereafter.', 'Support', 2),
('Can you update my existing app?', 'Absolutely! We specialize in app modernization and refactoring.', 'Services', 3);

-- 6.7 Site Settings
INSERT INTO "public"."site_settings" ("id", "site_name", "logo_url", "contact_email", "address", "play_store_url") VALUES 
(1, 'Aptic Studio', NULL, 'hello@apticstudio.com', '123 Innovation Dr, Tech City, NY', 'https://play.google.com/store/apps');

-- 6.8 Social Links
INSERT INTO "public"."social_links" ("platform", "url", "icon_name") VALUES 
('GitHub', 'https://github.com', 'Github'),
('LinkedIn', 'https://linkedin.com', 'Linkedin'),
('Twitter', 'https://twitter.com', 'Twitter'),
('Instagram', 'https://instagram.com', 'Instagram');

-- 6.9 Backfill Profiles
INSERT INTO "public"."profiles" ("id", "email", "role", "name", "created_at")
SELECT 
    au.id,
    au.email,
    'user', 
    COALESCE(au.raw_user_meta_data->>'full_name', au.raw_user_meta_data->>'name', ''),
    au.created_at
FROM auth.users au
ON CONFLICT (id) DO NOTHING;


----------- [SECTION 7: FINALIZATION] -----------
NOTIFY pgrst, 'reload schema';
